(
    MAIN_MENU,
    VIEW_ALERT,
    VIEW_ALERT_DETAILS,
    DELETE_CONFIRMATION,
    ALERT_TYPE,
    PAIR_INPUT,
    PRICE_INPUT,
    DESCRIPTION_INPUT,
    UPDATE_SELECTION,
    UPDATE_GET_VALUE,
) = range(10)
