(
    MAIN_MENU,
    VIEW_ALERT,
    VIEW_ALERT_DETAILS,
    DELETE_CONFIRMATION,
    ALERT_TYPE,
    PAIR_INPUT,
    PRICE_INPUT,
    DESCRIPTION_INPUT,
    UPDATE_SELECTION,
    UPDATE_GET_VALUE,
    # RSI States
    TIMEFRAME_INPUT,
    RSI_PERIOD_INPUT,
    RSI_CONDITION_INPUT,
    RSI_THRESHOLD_INPUT,
) = range(14)
